version: '2.16.0'
services:

  task_manager:
    build: ./
    container_name: task_manager
    restart: no
    depends_on:
      task_manager_db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://task_manager_db:5432/task_manager_db
      - SPRING_DATASOURCE_USERNAME=test
      - SPRING_DATASOURCE_PASSWORD=test


  task_manager_db:
    container_name: task_manager_db
    image: postgres
    restart: on-failure
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 10s
      retries: 10
    environment:
      POSTGRES_DB: task_manager_db
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql